name: Build GKI

on:
  workflow_call:
    inputs:
      RUNNER_TYPE:
        type: string
        default: 'self-hosted'
      TODO:
        type: string
      KSU:
        type: string
      BUILD_BOOTIMG:
        type: string
      LAST_BUILD:
        type: string
      STATUS:
        type: string
        default: 'BETA'

  workflow_dispatch:
    inputs:
      RUNNER_TYPE:
        description: Choose the runner type
        default: "self-hosted"
        type: choice
        options:
          - "self-hosted"
          - "ubuntu-latest"

      TODO:
        description: To do
        default: ""
        type: choice
        options:
          - "kernel"
          - "defconfig"

      KSU:
        description: KernelSU variant
        default: "Next"
        type: choice
        options:
          - "Next"

jobs:
  build:
    runs-on: ${{ inputs.RUNNER_TYPE }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Validate Inputs and Secrets
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          _error() {
              echo "❌ ERROR: $*"
              let ret++
          }

          ret=0
          # Check Secrets
          if [[ -z "$TG_CHAT_ID" ]]; then
            _error "Missing TG_CHAT_ID secret (Telegram Chat ID)"
          fi
          if [[ -z "$TG_BOT_TOKEN" ]]; then
            _error "Missing TG_BOT_TOKEN secret (Telegram Bot Token)"
          fi
          if [[ -z "$GH_TOKEN" ]]; then
            _error "Missing GH_TOKEN secret (GitHub PAT)"
          fi

          if [[ $ret -gt 0 ]]; then
            exit $ret
          fi

      - name: Install Dependencies
        run: |
          export MAN_DISABLE=true
          sudo rm -f /etc/apt/sources.list.d/yarn.list
          sudo apt update -y
          sudo apt install -y bc cpio flex bison aptitude gh git python3 \
                              tar perl wget curl lz4 zstd libarchive-tools aria2
          sudo aptitude install -y libssl-dev
          pip install lxml

      - name: Run Build Script
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          KSU: ${{ inputs.KSU }}
          BUILD_BOOTIMG: ${{ inputs.BUILD_BOOTIMG }}
          LAST_BUILD: ${{ inputs.LAST_BUILD }}
          TODO: ${{ inputs.TODO }}
          STATUS: ${{ inputs.STATUS }}
        run: |
          export GIT_CLONE_PROTECTION_ACTIVE=false
          chmod +x *.sh
          ./build.sh

      - name: Upload Artifacts (ZIP Only)
        id: upload-zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BASE_NAME }}-${{ github.run_number }}
          path: |
            artifacts/*.zip

      - name: Upload Artifacts (Info File)
        uses: actions/upload-artifact@v4
        with:
          name: info-${{ github.run_number }}
          path: artifacts/*.txt

      - name: Send Artifact Link to Telegram
        if: inputs.STATUS != 'BETA' && success()
        env:
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          MESSAGE_ID: ${{ env.MESSAGE_ID }}
          # Constructs the URL: Server URL + Repo + Run ID + Artifact ID
          ARTIFACT_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.upload-zip.outputs.artifact-id }}
        run: |
            MSG="✅ *Build Succeeded*

            📥 [Download Artifact]($ARTIFACT_URL)"

            # Send message replying to the original build start message
            curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
            -d chat_id="$TG_CHAT_ID" \
            -d reply_to_message_id="$MESSAGE_ID" \
            -d text="$MSG" \
            -d parse_mode="Markdown" \
            -d disable_web_page_preview=true
